fail_fast: true
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "v5.9.3"
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.910"
    hooks:
      - id: mypy
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: ^(tests|examples|docs)/.*
        additional_dependencies: [pep8-naming, flake8-docstrings]
