fail_fast: true
repos:
- repo: https://github.com/pre-commit/mirrors-isort
  rev: 'v5.10.1'
  hooks:
    - id: isort
      additional_dependencies: ['isort[pyproject]']
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.3.0'
    hooks:
    -   id: mypy
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        exclude: ^(tests|examples|docs)/
        additional_dependencies: [pep8-naming, flake8-docstrings]