fail_fast: true
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "v4.3.21"
    hooks:
      - id: isort
        additional_dependencies: ["isort[pyproject]"]
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.730"
    hooks:
      - id: mypy
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
      - id: flake8
        exclude: ^(tests|examples|docs)/*
        additional_dependencies: [pep8-naming, flake8-docstrings]
