# Do not use Travis Python to save some time.
language: generic

cache:
  directories:
    - $HOME/download
    - $HOME/miniconda

before_cache:
  - if ! [[ $TRAVIS_TAG ]]; then rm -rf $HOME/miniconda/conda-bld; fi
  - rm -rf $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history

before_install:
  - if test -e $HOME/miniconda/bin; then
      echo "miniconda already installed.";
    else
      echo "Installing miniconda.";
      rm -rf $HOME/miniconda;
      mkdir -p $HOME/download;
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
      bash $HOME/download/miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      hash -r;
      conda config --set always_yes yes --set changeps1 no;
      conda update -q conda;
      conda info -a;
      conda create -q -n test-environment python=3.7 r-essentials rpy2;
    fi

install:
  - export PATH="$HOME/miniconda/bin:$PATH"
  # Useful for debugging any issues with conda
  - conda info -a
  - source activate test-environment
  - R < packages.R --no-save
  - pip install -r requirements-dev.txt

script:
  - PYTHONPATH=. pytest tests/
  - PYTHONPATH=. pytest --mypy -m mypy tests/