# Do not use Travis Python to save some time.
language: generic

cache:
  directories:
    - $HOME/download
    - $HOME/miniconda

before_cache:
  - if ! [[ $TRAVIS_TAG ]]; then rm -rf $HOME/miniconda/conda-bld; fi
  - rm -rf $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history

before_install:
  # Caches the conda installation and env across builds.
  - if test -e $HOME/miniconda/bin; then
      echo "miniconda already installed.";
    else
      echo "Installing miniconda.";
      rm -rf $HOME/miniconda;
      mkdir -p $HOME/download;
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
      bash $HOME/download/miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      hash -r;
      conda config --set always_yes yes --set changeps1 no;
      conda update -q conda;
      conda config --add channels conda-forge;
      conda info -a;
      conda env create -f dev-env.yml;
    fi

install:
  - export PATH="$HOME/miniconda/bin:$PATH"
  # Useful for debugging any issues with conda.
  - conda info -a
  - source activate epysurv-dev
  - pip install -r requirements-dev.txt

script:
  - black --check epysurv
  - PYTHONPATH=. pytest --mypy -m mypy tests/
  - PYTHONPATH=. pytest --cov=epysurv tests/

after_success:
  - codecov
